### PR TITLE
#358, #478 Update nanoid to use restricted alphabet

### LINKED ISSUE #358: component names ending with '-' will cause conditions to crash
**Describe the bug**
component names ending with '-' `abdef-` will make condition logic unparsable. Conditions using these fields can't be persisted for this reason 

**To Reproduce**

1. create a list
2. create a radio component
3. Set component name to be "abcdef-" 
4. save the component
5. create a condition using this component 
6. save the condition - this error appears in the runner
```
[1] [1613134842373] ERROR        (18894 on Jens-MacBook-Pro.local):
[1]     tags: [
[1]       "error"
[1]     ]
[1]     data: {
[1]       "statusCode": 500,
[1]       "data": null,
[1]       "message": "unexpected TOP: =="
[1]     }
```
7. refresh the page
8. navigating back to the conditions list, you will see the condition is gone

**Expected behavior**
The condition should be persisted 

**Screenshots**

**Repository**
- Designer, model

**Desktop (please complete the following information):**
- universal 

Fix:
the autogenerated IDs (nanoid) need to use a custom alphabet that does not generate `-` at the end (or use `-` at all)

### LINKED ISSUE #478: Autogenerated names shouldn't start with a number
**Describe the bug**
When a section or field name starts with a number it isn't a valid variable name so subsequent use in a condition will fail.

**To Reproduce**

1. Manually change the name of a section or field so it starts with a number.
2. Create a condition that uses that field
3. Deploy the form and attempt to complete

**Expected behavior**
The designer should generate valid names. 
Validation should prevent a form running if field names are incorrect.
Conditions should evaluate successfully. 

**Repository**

- designer
- model

### PR DESCRIPTION
**Pull request by superafroman**
# Description

Closes #358 
Closes #478 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manual checking.

# Checklist:

- [x] My changes do not introduce any new linting errors
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and versioning
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have rebased onto master and there are no code conflicts
- [ ] I have checked deployments are working in all environments
- [ ] I have updated the architecture diagrams as per Contribute.md

### CODE REVIEW

File: designer/client/random-id.tsx [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import { customAlphabet } from "nanoid";
+
```
Comment (jenbutongit) [inline designer/client/random-id.tsx:2]: this should just be named a .ts file - we should just reserve .tsx for those with tsx in.

**Review by jenbutongit — CHANGES_REQUESTED** [review]

File: designer/client/random-id.tsx (hunk 1 above)
Comment (superafroman) [reply designer/client/random-id.tsx]: Good catch 👍

File: designer/client/component-create.js [hunk 2]
```diff
@@ -1,7 +1,8 @@
 import React from "react";
-import ComponentTypeEdit from "./component-type-edit";
+import ComponentTypeEdit from "./ComponentTypeEdit";
 import { clone, ComponentTypes } from "@xgovformbuilder/model";
 import { DataContext } from "./context";
+import randomId from "./random-id";
```
[the remark this answers is not in the document]
Comment (superafroman) [reply designer/client/component-create.js]: Done

**Review by jenbutongit — APPROVED** [review]
