### PR TITLE
Fix: close menu flyouts on save

### LINKED ISSUE #699: Main menu flyouts don't close on save
**Describe the bug**
Flyouts which are initialised directly from the main menu (e.g. 'Add page') don't close when the user saves their changes. Other flyouts (e.g. the 'Add list' flyout).

**To Reproduce**

1. Go to the main designer view
2. Click on 'Add page', 'Add link', 'Fees' or 'Summary behaviour'
3. Make a valid edit
4. Save
4. See that the flyout stays open

**Expected behavior**
The window should close - without this the behaviour is inconsistent and the user gets no visual feedback that the save has been processed. 

**Screenshots**
n/a

**Repository**

- designer

**Desktop (please complete the following information):**

Think this happens everywhere, but have specifically seen it on:

- OS: macOS
- Browser: Firefox developer edition 
- Version: 95.0b6

**Smartphone (please complete the following information):**
n/a

**Additional context**
I've pushed a rough [fix for this in a temporary branch in our fork](https://github.com/davidbiddle/digital-form-builder/commit/32fcf6cfd6e7187dcfdc6810ad78172d05face54) - happy to raise a PR once I've written a test and cleaned it up a bit.

### PR DESCRIPTION
**Pull request by DavidBiddle**
# Description
Fixes #699 
Includes:
- Fixes onCreate calls in Menu component
- Remove onCreate prop from menu items which don't use it
- Slight edit to DeclarationEdit component so the save logic matches the other menu components

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] Manually testing that the window closes on Save
- [ ] Some manual regression testing to make sure saves happen correctly
- [ ] Added automated test

# Checklist:

- [ ] My changes do not introduce any new linting errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and versioning
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have rebased onto main and there are no code conflicts
- [ n/a ] I have checked deployments are working in all environments
- [ n/a ] I have updated the architecture diagrams as per Contribute.md

### CODE REVIEW

File: designer/client/components/Menu/Menu.tsx [hunk 1]
```diff
@@ -123,13 +123,13 @@ export default function Menu({ updateDownloadedAt, id }: Props) {
       )}
       {outputs.isVisible && (
         <Flyout title="Edit Outputs" onHide={outputs.hide} width="xlarge">
-          <OutputsEdit data={data} onCreate={outputs.hide} />
+          <OutputsEdit data={data} />
```
Comment (jenbutongit) [inline designer/client/components/Menu/Menu.tsx:126]: Ah, this should be using context instead of the prop but I'll open a new issue for it

**Review by jenbutongit — APPROVED** [review]
LGTM
