### PR TITLE
fix: visualisation link a11y fixes

### LINKED ISSUE #701: Links between pages aren't accessible for keyboard-only users
**Describe the bug**
The polylines that represent links between pages in the visualisation can't be tabbed into. This means they can't be edited at all by keyboard-only users.

**To Reproduce**

1. Open any form with at least one link in the designer
2. Tab through the items
3. Note that you can't tab into the links

**Expected behavior**
Links should be keyboard accessible.

**Screenshots**
n/a

**Repository**

- designer

**Desktop (please complete the following information):**
I believe this happens everywhere (polylines aren't focusable by default), but have observed it in:

- OS: macOS
- Browser: Firefox developer edition
- Version: 95.0b6

**Smartphone (please complete the following information):**

- n/a

**Additional context**
I've pushed a rough [fix for this in a temporary branch in our fork](https://github.com/davidbiddle/digital-form-builder/commit/9015e536797f417541c4266d19f0fc2672d7ba1b) - happy to raise a PR once I've written a test and cleaned it up a bit.

### LINKED ISSUE #702: Issues with links between pages in VoiceOver
**Describe the bug**
The polylines that represent links between pages in the visualisation have 2 closely related issues in VoiceOver:
- They can be selected via Voiceover's navigation, but only respond to click events (so the user can't press Enter to select them)
- They aren't currently labelled - this means all of the links just read 'Image' in a screen reader and the user doesn't know that they're interactive controls

**To Reproduce**

1. Open any form with at least one link in the designer
2. Use a screen reader to navigate through the items in the visualisation
3. Note that the links don't indicate that they're interactive controls, or give any contextual information about which pages they link

**Expected behavior**
In a screen reader the links should be labelled appropriately so that they give:
- an indication of their interactivity
- information about which pages they connect

**Screenshots**
n/a

**Repository**

- designer

**Desktop (please complete the following information):**
I believe this will happen in any screen reader, but have observed it in:

- OS: macOS
- Browser: Safari 
- Version: 15.1
- Screen reader:  VoiceOver

- **Smartphone (please complete the following information):**

- n/a

**Additional context**
I think implementing #491 would be the best fix for this, but that looks like a significantly bigger bit of work. 

I've pushed a rough [fix for this in a temporary branch in our fork](https://github.com/davidbiddle/digital-form-builder/commit/9015e536797f417541c4266d19f0fc2672d7ba1b) - happy to raise a PR once I've written a test and cleaned it up a bit. This will also fix #701

### PR DESCRIPTION
**Pull request by DavidBiddle**
# Description

Fixes #701 
Fixes #702 

- Link polylines in the visualisation now have `role="button"` and an appropriate `title` so that screen reader users know they can be used to edit the corresponding link
- Space bar and enter events on the link polyline will open the Edit Link menu - thi smatches the behaviour of native buttons

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] Manual testing with keyboard navigation
- [ ] Manual testing in VoiceOver
- [ ] Automated tests added

# Checklist:

- [ ] My changes do not introduce any new linting errors
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ n/a ] I have made corresponding changes to the documentation and versioning
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have rebased onto main and there are no code conflicts
- [ n/a ] I have checked deployments are working in all environments
- [ n/a ] I have updated the architecture diagrams as per Contribute.md

### CODE REVIEW

File: designer/client/components/Visualisation/Lines.tsx [hunk 1]
```diff
@@ -57,10 +57,21 @@ export class Lines extends React.Component<Props, State> {
               <g key={pointsString}>
                 <polyline
                   onClick={() => this.editLink(edge)}
+                  onKeyPress={(event) =>
+                    event.key === "Enter" || event.key === " "
+                      ? this.editLink(edge)
+                      : null
+                  }
```
Comment (jenbutongit) [inline designer/client/components/Visualisation/Lines.tsx:64]: could you add this as a class method please (like how it's done for onClick, `onClick={() => this.editLink(edge)}`). It will just clean up the markup and make things easier to follow.

 I suppose you could even change editLink to accept event and edge. so both onClick and onKeyPress would look like this `(event) => this.editLink(event, edge)`?

**Review by jenbutongit — CHANGES_REQUESTED** [review]
just one minor refactor, otherwise LGTM!

File: designer/client/components/Visualisation/Lines.tsx (hunk 1 above)
Comment (DavidBiddle) [reply designer/client/components/Visualisation/Lines.tsx]: Done! I decided against making editLink accept `event` in the end - accepting both MouseEvent and KeyboardEvent made the types a bit untidy (maybe just me being unfamiliar with TypeScript)

Comment (jenbutongit) [reply designer/client/components/Visualisation/Lines.tsx]: Make sense. Thanks!

**Review by jenbutongit — APPROVED** [review]
🪄!
